# URI for database connection, leave empty if using address and credential settings directly
uri: mongodb://localhost:27017/openim_v3?maxPoolSize=20
# List of MongoDB server addresses
address: [ ]
# Name of the database
database: openim_v3
# Username for database authentication
username:
# Password for database authentication
password:
# Authentication source for database authentication, if use root user, set it to admin
authSource:
# Maximum number of connections in the connection pool
maxPoolSize: 20
# Maximum number of retry attempts for a failed database connection
maxRetry: 10
